"""initial_schema

Revision ID: 8623ca4b5093
Revises:
Create Date: 2025-11-19 05:09:24.831391

"""
from alembic import op
import sqlalchemy as sa
from app.database import GUID


# revision identifiers, used by Alembic.
revision = '8623ca4b5093'
down_revision = None
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('projects',
    sa.Column('id', GUID(length=36), nullable=False),
    sa.Column('project_name', sa.String(length=255), nullable=False),
    sa.Column('business_name', sa.String(length=255), nullable=False),
    sa.Column('industry', sa.String(length=100), nullable=False),
    sa.Column('currency', sa.String(length=3), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('advisor_notes', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('dcf_cash_flows',
    sa.Column('id', GUID(length=36), nullable=False),
    sa.Column('project_id', GUID(length=36), nullable=False),
    sa.Column('year_index', sa.Integer(), nullable=False),
    sa.Column('year_label', sa.String(length=50), nullable=False),
    sa.Column('cash_flow', sa.Numeric(precision=15, scale=2), nullable=False),
    sa.Column('discounted_cash_flow', sa.Numeric(precision=15, scale=2), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_dcf_cash_flows_project_id'), 'dcf_cash_flows', ['project_id'], unique=False)
    op.create_table('dcf_parameters',
    sa.Column('id', GUID(length=36), nullable=False),
    sa.Column('project_id', GUID(length=36), nullable=False),
    sa.Column('base_metric', sa.String(length=50), nullable=False),
    sa.Column('base_year', sa.Integer(), nullable=False),
    sa.Column('discount_rate', sa.Numeric(precision=10, scale=6), nullable=False),
    sa.Column('projection_years', sa.Integer(), nullable=False),
    sa.Column('terminal_method', sa.String(length=50), nullable=False),
    sa.Column('terminal_growth_rate', sa.Numeric(precision=10, scale=6), nullable=True),
    sa.Column('terminal_multiple', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('use_explicit_cash_flows', sa.Boolean(), nullable=False),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_dcf_parameters_project_id'), 'dcf_parameters', ['project_id'], unique=True)
    op.create_table('dcf_results',
    sa.Column('id', GUID(length=36), nullable=False),
    sa.Column('project_id', GUID(length=36), nullable=False),
    sa.Column('present_value_of_cash_flows', sa.Numeric(precision=15, scale=2), nullable=False),
    sa.Column('terminal_value', sa.Numeric(precision=15, scale=2), nullable=False),
    sa.Column('present_value_of_terminal_value', sa.Numeric(precision=15, scale=2), nullable=False),
    sa.Column('dcf_equity_value', sa.Numeric(precision=15, scale=2), nullable=False),
    sa.Column('currency', sa.String(length=3), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_dcf_results_project_id'), 'dcf_results', ['project_id'], unique=True)
    op.create_table('financial_inputs',
    sa.Column('id', GUID(length=36), nullable=False),
    sa.Column('project_id', GUID(length=36), nullable=False),
    sa.Column('year', sa.Integer(), nullable=False),
    sa.Column('revenue', sa.Numeric(precision=15, scale=2), nullable=False),
    sa.Column('cogs', sa.Numeric(precision=15, scale=2), nullable=True),
    sa.Column('gross_profit', sa.Numeric(precision=15, scale=2), nullable=True),
    sa.Column('operating_expenses', sa.Numeric(precision=15, scale=2), nullable=True),
    sa.Column('ebitda', sa.Numeric(precision=15, scale=2), nullable=True),
    sa.Column('sde', sa.Numeric(precision=15, scale=2), nullable=True),
    sa.Column('net_income', sa.Numeric(precision=15, scale=2), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_financial_inputs_project_id'), 'financial_inputs', ['project_id'], unique=False)
    op.create_table('full_valuation_summaries',
    sa.Column('id', GUID(length=36), nullable=False),
    sa.Column('project_id', GUID(length=36), nullable=False),
    sa.Column('market_value_mid', sa.Numeric(precision=15, scale=2), nullable=True),
    sa.Column('dcf_value', sa.Numeric(precision=15, scale=2), nullable=True),
    sa.Column('asset_value', sa.Numeric(precision=15, scale=2), nullable=True),
    sa.Column('weight_market', sa.Numeric(precision=5, scale=4), nullable=False),
    sa.Column('weight_dcf', sa.Numeric(precision=5, scale=4), nullable=False),
    sa.Column('weight_asset', sa.Numeric(precision=5, scale=4), nullable=False),
    sa.Column('final_value_low', sa.Numeric(precision=15, scale=2), nullable=False),
    sa.Column('final_value_mid', sa.Numeric(precision=15, scale=2), nullable=False),
    sa.Column('final_value_high', sa.Numeric(precision=15, scale=2), nullable=False),
    sa.Column('currency', sa.String(length=3), nullable=False),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_full_valuation_summaries_project_id'), 'full_valuation_summaries', ['project_id'], unique=True)
    op.create_table('normalization_entries',
    sa.Column('id', GUID(length=36), nullable=False),
    sa.Column('project_id', GUID(length=36), nullable=False),
    sa.Column('year', sa.Integer(), nullable=False),
    sa.Column('category', sa.String(length=100), nullable=False),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('amount', sa.Numeric(precision=15, scale=2), nullable=False),
    sa.Column('is_addback', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_normalization_entries_project_id'), 'normalization_entries', ['project_id'], unique=False)
    op.create_table('normalized_financials',
    sa.Column('id', GUID(length=36), nullable=False),
    sa.Column('project_id', GUID(length=36), nullable=False),
    sa.Column('year', sa.Integer(), nullable=False),
    sa.Column('normalized_revenue', sa.Numeric(precision=15, scale=2), nullable=False),
    sa.Column('normalized_ebitda', sa.Numeric(precision=15, scale=2), nullable=True),
    sa.Column('normalized_sde', sa.Numeric(precision=15, scale=2), nullable=True),
    sa.Column('normalized_net_income', sa.Numeric(precision=15, scale=2), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_normalized_financials_project_id'), 'normalized_financials', ['project_id'], unique=False)
    op.create_table('valuation_summaries',
    sa.Column('id', GUID(length=36), nullable=False),
    sa.Column('project_id', GUID(length=36), nullable=False),
    sa.Column('value_low', sa.Numeric(precision=15, scale=2), nullable=False),
    sa.Column('value_mid', sa.Numeric(precision=15, scale=2), nullable=False),
    sa.Column('value_high', sa.Numeric(precision=15, scale=2), nullable=False),
    sa.Column('method', sa.String(length=50), nullable=False),
    sa.Column('multiple_low', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('multiple_mid', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('multiple_high', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('base_metric_value', sa.Numeric(precision=15, scale=2), nullable=True),
    sa.Column('base_metric_type', sa.String(length=50), nullable=True),
    sa.Column('currency', sa.String(length=3), nullable=False),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_valuation_summaries_project_id'), 'valuation_summaries', ['project_id'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_valuation_summaries_project_id'), table_name='valuation_summaries')
    op.drop_table('valuation_summaries')
    op.drop_index(op.f('ix_normalized_financials_project_id'), table_name='normalized_financials')
    op.drop_table('normalized_financials')
    op.drop_index(op.f('ix_normalization_entries_project_id'), table_name='normalization_entries')
    op.drop_table('normalization_entries')
    op.drop_index(op.f('ix_full_valuation_summaries_project_id'), table_name='full_valuation_summaries')
    op.drop_table('full_valuation_summaries')
    op.drop_index(op.f('ix_financial_inputs_project_id'), table_name='financial_inputs')
    op.drop_table('financial_inputs')
    op.drop_index(op.f('ix_dcf_results_project_id'), table_name='dcf_results')
    op.drop_table('dcf_results')
    op.drop_index(op.f('ix_dcf_parameters_project_id'), table_name='dcf_parameters')
    op.drop_table('dcf_parameters')
    op.drop_index(op.f('ix_dcf_cash_flows_project_id'), table_name='dcf_cash_flows')
    op.drop_table('dcf_cash_flows')
    op.drop_table('projects')
    # ### end Alembic commands ###
