"""
Report Builder Service
Generates Markdown reports for Quick and Standard valuations
"""
from sqlalchemy.orm import Session
from uuid import UUID
from datetime import datetime
from typing import Dict
from app.models import (
    Project,
    ValuationSummary,
    ValuationResults,
    FinancialInputs,
    ScoreResult,
    ScoreDimensionResult,
    Report,
    ReportTemplate
)
from app.services.score_engine import get_score_summary


def generate_quick_report_markdown(db: Session, project_id: UUID) -> str:
    """
    Generate Quick Valuation report in Markdown format

    Sections:
    - Executive Summary
    - Financial Overview
    - Valuation Results
    - Methodology
    - Disclaimer
    """
    project = db.query(Project).filter_by(id=project_id).first()
    if not project:
        raise ValueError(f"Project {project_id} not found")

    summary = db.query(ValuationSummary).filter_by(project_id=project_id).first()
    if not summary:
        raise ValueError("No valuation summary found. Please run quick valuation first.")

    financial_inputs = db.query(FinancialInputs).filter_by(
        project_id=project_id,
        year=0
    ).first()

    valuation_results = db.query(ValuationResults).filter_by(
        project_id=project_id
    ).all()

    # Build report
    report = f"""# Quick Valuation Report

**Business Name:** {project.name}
**Industry:** {project.industry or 'Not specified'}
**Report Date:** {datetime.now().strftime('%B %d, %Y')}
**Report Type:** Quick Valuation

---

## Executive Summary

This Quick Valuation provides a preliminary estimate of your business value based on financial metrics and industry standards. The estimated value range is:

**${summary.value_low:,.2f} - ${summary.value_high:,.2f}**

**Mid-point estimate: ${summary.value_mid:,.2f}**

This valuation uses established methodologies including revenue multiples, EBITDA multiples, and asset-based approaches appropriate for your industry.

---

## Financial Overview

"""

    if financial_inputs:
        report += f"""
### Current Year Financials

- **Annual Revenue:** ${financial_inputs.revenue:,.2f}
"""
        if financial_inputs.net_profit:
            report += f"- **Net Profit:** ${financial_inputs.net_profit:,.2f}\n"
        if financial_inputs.ebitda:
            report += f"- **EBITDA:** ${financial_inputs.ebitda:,.2f}\n"
        if financial_inputs.total_assets:
            report += f"- **Total Assets:** ${financial_inputs.total_assets:,.2f}\n"
        if financial_inputs.total_liabilities:
            report += f"- **Total Liabilities:** ${financial_inputs.total_liabilities:,.2f}\n"

    report += """
---

## Valuation Results

### Summary

"""

    report += f"""
| Metric | Value |
|--------|-------|
| Low Estimate | ${summary.value_low:,.2f} |
| Mid Estimate | ${summary.value_mid:,.2f} |
| High Estimate | ${summary.value_high:,.2f} |
| Primary Method | {summary.primary_method.replace('_', ' ').title()} |

### Methodology Breakdown

"""

    for result in valuation_results:
        report += f"""
#### {result.method.replace('_', ' ').title()}

- **Valuation:** ${result.value:,.2f}
- **Confidence:** {result.confidence.title()}
- **Notes:** {result.notes}

"""

    report += """
---

## Valuation Methodology

This Quick Valuation uses industry-standard approaches:

1. **Revenue Multiple Method:** Applies industry-specific multiples to annual revenue
2. **EBITDA Multiple Method:** Values the business based on earnings before interest, taxes, depreciation, and amortization
3. **Asset-Based Method:** Calculates value based on net assets

The final valuation range considers all applicable methods and their relative confidence levels.

---

## Important Disclaimer

**This is a preliminary estimate only** and should not be used as the sole basis for any financial, legal, or business decisions.

### Limitations

- Simplified methodologies
- Does not account for market conditions, competitive positioning, customer concentration, intellectual property, management quality, and many other qualitative factors

### Recommendation

For any significant business transaction, please consult:
- Certified Business Valuator (CBV)
- Certified Public Accountant (CPA)
- M&A Specialist

---

*Report generated by Exit Builder - Quick Valuation*
"""

    return report


def generate_standard_report_markdown(db: Session, project_id: UUID) -> str:
    """
    Generate Standard Valuation report in Markdown format

    Sections:
    - Executive Summary
    - Business Overview
    - Financial Summary
    - Scorecard Summary
    - Valuation Results
    - Recommendations
    - Disclaimer
    """
    project = db.query(Project).filter_by(id=project_id).first()
    if not project:
        raise ValueError(f"Project {project_id} not found")

    summary = db.query(ValuationSummary).filter_by(project_id=project_id).first()
    if not summary:
        raise ValueError("No valuation summary found")

    score_result = db.query(ScoreResult).filter_by(project_id=project_id).first()
    if not score_result:
        raise ValueError("No score result found. Please run compute_scorecard first.")

    financial_inputs = db.query(FinancialInputs).filter_by(
        project_id=project_id,
        year=0
    ).first()

    score_summary = get_score_summary(db, project_id)

    # Build report
    report = f"""# Exit Ready MPSP - Standard Valuation Report

**Business Name:** {project.name}
**Industry:** {project.industry or 'Not specified'}
**Report Date:** {datetime.now().strftime('%B %d, %Y')}
**Report Type:** Exit Ready Standard Valuation

---

## Executive Summary

Congratulations on taking this important step toward making your business Exit Ready. This comprehensive report provides:

1. **Exit Readiness Score:** {score_result.total_score}/100 (Rating: **{score_result.rating}**)
2. **Adjusted Business Valuation:** ${summary.value_low:,.2f} - ${summary.value_high:,.2f}
3. **Valuation Adjustment Factor:** {score_result.valuation_adjustment_factor}x (based on Exit Readiness)

Your business has been evaluated across five critical dimensions that impact both its sellability and valuation. This report identifies your strengths and areas for improvement.

---

## Business Overview

**Company:** {project.name}
**Industry:** {project.industry or 'Not specified'}

"""

    if project.description:
        report += f"**Description:** {project.description}\n\n"

    report += """
---

## Financial Summary

"""

    if financial_inputs:
        report += f"""
### Current Year Financials

- **Annual Revenue:** ${financial_inputs.revenue:,.2f}
"""
        if financial_inputs.net_profit:
            report += f"- **Net Profit:** ${financial_inputs.net_profit:,.2f}\n"
            if financial_inputs.revenue and financial_inputs.revenue > 0:
                margin = (financial_inputs.net_profit / financial_inputs.revenue) * 100
                report += f"- **Net Profit Margin:** {margin:.1f}%\n"

        if financial_inputs.ebitda:
            report += f"- **EBITDA:** ${financial_inputs.ebitda:,.2f}\n"
            if financial_inputs.revenue and financial_inputs.revenue > 0:
                ebitda_margin = (financial_inputs.ebitda / financial_inputs.revenue) * 100
                report += f"- **EBITDA Margin:** {ebitda_margin:.1f}%\n"

        if financial_inputs.total_assets:
            report += f"- **Total Assets:** ${financial_inputs.total_assets:,.2f}\n"
        if financial_inputs.total_liabilities:
            report += f"- **Total Liabilities:** ${financial_inputs.total_liabilities:,.2f}\n"
            if financial_inputs.total_assets:
                net_assets = financial_inputs.total_assets - financial_inputs.total_liabilities
                report += f"- **Net Assets:** ${net_assets:,.2f}\n"

    report += """
---

## Exit Readiness Scorecard

"""

    report += f"""
### Overall Score: {score_result.total_score}/100

**Rating: {score_result.rating}**

"""

    rating_descriptions = {
        "A": "**Excellent** - Your business is highly exit-ready with strong fundamentals and transferability.",
        "B": "**Good** - Your business is well-positioned for exit with minor improvements recommended.",
        "C": "**Fair** - Your business has potential but requires moderate improvements for optimal exit readiness.",
        "D": "**Needs Improvement** - Significant work is needed to make your business attractive to buyers."
    }

    report += rating_descriptions.get(score_result.rating, "") + "\n\n"

    report += """
### Dimension Scores

| Dimension | Score | Weight | Assessment |
|-----------|-------|--------|------------|
"""

    for dim in score_summary["dimensions"]:
        report += f"| {dim['name']} | {dim['score']} | {dim['weight']:.0%} | {dim['comment']} |\n"

    report += """

### Strengths

"""

    # Identify strengths (top scoring dimensions)
    sorted_dims = sorted(score_summary["dimensions"], key=lambda x: x["score"], reverse=True)
    top_dims = sorted_dims[:2]

    for dim in top_dims:
        if dim["score"] >= 15:
            report += f"- **{dim['name']}:** {dim['comment']}\n"

    report += """

### Areas for Improvement

"""

    # Identify weaknesses (bottom scoring dimensions)
    bottom_dims = sorted_dims[-2:]

    for dim in bottom_dims:
        if dim["score"] < 15:
            report += f"- **{dim['name']}:** {dim['comment']}\n"

    report += """
---

## Valuation Results

### Adjusted Valuation

"""

    # Calculate baseline (before adjustment)
    adjustment = score_result.valuation_adjustment_factor
    baseline_mid = summary.value_mid / adjustment

    report += f"""
Your business valuation has been adjusted based on your Exit Readiness score:

- **Baseline Valuation:** ${baseline_mid:,.2f}
- **Adjustment Factor:** {adjustment}x (Rating {score_result.rating})
- **Adjusted Valuation Range:** ${summary.value_low:,.2f} - ${summary.value_high:,.2f}
- **Adjusted Mid-Point:** ${summary.value_mid:,.2f}

The adjustment factor reflects how buyer perception and risk assessment impact value:
- **Rating A (1.10x):** Premium valuation for highly transferable businesses
- **Rating B (1.00x):** Standard market valuation
- **Rating C (0.90x):** Discount for moderate transfer risk
- **Rating D (0.80x):** Significant discount for high transfer risk

---

## Recommendations

Based on your Exit Readiness assessment, we recommend:

"""

    # Generate recommendations based on weak dimensions
    recommendations_map = {
        "OWNER_DEP": "1. **Reduce Owner Dependency:** Build a strong management team, delegate key responsibilities, and document critical processes so the business can operate without you.\n",
        "CUSTOMER_CONC": "2. **Diversify Customer Base:** Reduce reliance on top customers by developing new revenue streams and establishing long-term contracts with existing clients.\n",
        "SYSTEMS": "3. **Strengthen Systems & Processes:** Document standard operating procedures, invest in modern technology systems, and implement a CRM for customer management.\n",
        "FIN_QUALITY": "4. **Improve Financial Quality:** Maintain clean, professional financial records and work to increase recurring revenue and profit margins.\n",
        "GROWTH": "5. **Enhance Growth & Market Position:** Focus on sustainable growth, strengthen your competitive advantage, and improve market positioning.\n"
    }

    for dim in bottom_dims:
        if dim["score"] < 15:
            rec = recommendations_map.get(dim["code"])
            if rec:
                report += rec

    report += """

### Next Steps

1. **Address priority improvements** identified in this report
2. **Re-assess in 6 months** to track progress
3. **Consult with advisors** (M&A specialists, CPAs, business coaches)
4. **Consider engaging** Capital Link for Exit Ready program implementation

---

## Important Disclaimer

**This report provides educational estimates and guidance** and should not be used as the sole basis for any financial, legal, or business decisions.

### Limitations

- Valuations are estimates based on simplified methodologies
- Does not constitute a formal business appraisal
- Actual transaction values may vary significantly based on market conditions, buyer motivations, deal structure, and many other factors
- Scorecard is based on self-reported information

### Professional Advice

For any significant business transaction, legal matter, tax purpose, or financial decision, please consult:
- Certified Business Valuator (CBV)
- Certified Public Accountant (CPA)
- M&A Advisor or Investment Banker
- Business Attorney

---

*Report generated by Exit Builder - Exit Ready MPSP Standard Valuation*
*© Capital Link - Exit Ready Program*

"""

    return report


def save_report(db: Session, project_id: UUID, template_code: str, content: str) -> Report:
    """
    Save a generated report to the database
    """
    # Get report template
    template = db.query(ReportTemplate).filter_by(code=template_code).first()
    if not template:
        raise ValueError(f"Report template '{template_code}' not found")

    # Create report
    report = Report(
        project_id=project_id,
        template_id=template.id,
        content=content,
        format="markdown"
    )

    db.add(report)
    db.commit()
    db.refresh(report)

    return report
